"""Add date_added, date_deleted, date_blacklisted to Product

Revision ID: 18e3ee86d88d
Revises: de672f03517c
Create Date: 2025-04-24 15:14:11.060600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e3ee86d88d'
down_revision = 'de672f03517c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_blacklisted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_deleted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('date_deleted')
        batch_op.drop_column('date_blacklisted')
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
