"""Add restock fields to Product

Revision ID: cd3f5b249b4f
Revises: 18e3ee86d88d
Create Date: 2025-06-07 17:18:17.807759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3f5b249b4f'
down_revision = '18e3ee86d88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_restocked', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reorder_lead_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('safety_stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('safety_stock')
        batch_op.drop_column('reorder_lead_time')
        batch_op.drop_column('last_restocked')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
