"""Add is_blacklisted and sales relationship

Revision ID: de672f03517c
Revises: 2527d0eef1c3
Create Date: 2025-04-24 14:58:33.721310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de672f03517c'
down_revision = '2527d0eef1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blacklisted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_blacklisted')

    # ### end Alembic commands ###
